### ISSUE TITLE
Taggle product should show Taggle in the about dialog

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineup_product#1]
![image](https://user-images.githubusercontent.com/4129755/36339654-eb6308fe-13ca-11e8-85af-4dc7f43da8b9.png)

**Comment by thinkh** [comment]
@mstreit Could you please suggest a short description? Afterwards I will take care about changing the title, description and the image.

**Comment by mstreit** [comment]
Taggle is a scalable visualization technique for exploring, ranking, and aggregating tabular data.
More details about the technique can be found at http://caleydo.org/tools/taggle/.

Thanks!

**Comment by thinkh** [comment]
Done.

![image](https://user-images.githubusercontent.com/5851088/36546178-069fbb34-17eb-11e8-9a89-cefb9031568a.png)
